### ISSUE TITLE
Mods Do Not Load

### ISSUE THREAD

**Issue by JEB12345** [frantjc/sindri#48]
Hello,

I have been running valheimw for a few weeks now and it runs well as a vanilla server. I recently tried to load some server side mods, but it seems that none of the mods load. I am able to see the system pull the mods listed in my compose.yaml file and put them into the BepInEx plugins folder. However, the image doesn't seem to load the mods (and possibly BepInEx) when I start it up.

Below is my compose.yaml file:
```
services:
  valheimw:
    image: ghcr.io/frantjc/valheimw
    command:
      # The name of the Valheim server's save files.
      # If they already exist, it will load them. If
      # they do not, it will create them.
      # Optional. Default "sindri".

[log.txt](https://github.com/user-attachments/files/18834780/log.txt)

      # - --world=hello
      # The name of the Valheim server as a player would
      # see it in-game when connecting to it.
      # Optional. Default "sindri".
      # - --name=there
      # Can be specified if you want to run a
      # pre-release version of the Valheim server.
      # Optional.
      # - --beta=public-test
      # - --beta-password=yesimadebackups
      # Browse https://valheim.thunderstore.io/ for available mods.
      # Names are case-sensitive.
      # Optional.
      - --mod=SpikeHimself/XPortal
      - --mod=ValheimModding/Jotunn
      - --save-interval=15m
    environment:
      # The password you will use to connect to your server.
      # Required. Must be at least 5 characters, and cannot
      # be contained within your world name. Default world name
      # is "sindri".
      VALHEIM_PASSWORD: test
    volumes:
      # `valheimw` caches stuff here and the Valheim server's
      # save data is here by default.
      - ./saves:/home/valheimw/.cache
    ports:
      # Expose the Valheim server's port.
      # If you change the Valheim server's port from its default,
      # via `--port`, ensure that this is changed to match.
      - 2456:2456/udp
      - 8080:8080
networks: {}
```

I also uploaded a log file with the terminal output from starting the docker compose.

[log.txt](https://github.com/user-attachments/files/18834786/log.txt)
